### ISSUE TITLE
Map not showing 

### ISSUE THREAD

**Issue by saprative** [makinacorpus/django-leaflet#155]
Please document how to add use google maps with django leaflet.

**Comment by W7PEA** [comment]
@saprative  This is in the Leaflet FAQ:

https://github.com/Leaflet/Leaflet/blob/master/FAQ.md
"
**I want to use Google Maps API tiles with Leaflet, can I do that?**
The problem with Google is that its Terms of Use forbid any means of tile access other than through the Google Maps API.  
You can add the Google Maps API as a Leaflet layer with a plugin. But note that the map experience will not be perfect, because Leaflet will just act as a proxy to the Google Maps JS engine, so you won't get all the performance and usability benefits of using Leaflet when the Google layer is on.
"
